name: docker image deploy

on:
  push:
    branches: ['release/*']

env:
  DOCKER_IMAGE_PATH: ${{ secrets.DOCKERHUB_USERNAME }}/i2pd-docker

jobs:
  docker_image_deploy:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set variables
        id: set-var
        run: |
          echo ::set-output name=DOCKER_IMAGE_TAG::${GITHUB_REF##*/}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_PATH }}:${{ steps.set-var.outputs.DOCKER_IMAGE_TAG }}
